name: ğŸ’¾ ZenSpace Server
on: [push]
jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #   #   - uses: actions/checkout@v3
  #   #   - name: â˜• Setting up Java (17)
  #   #     uses: actions/setup-java@v3
  #   #     with:
  #   #       java-version: 17
  #   #       distribution: "adopt"
  #   #       cache: gradle
  #     # - name: ğŸ§ª Test ZenSpace
  #     #   continue-on-error: true
  #     #   run: |
  #     #     cd ./packages/server
  #     #     chmod +x gradlew
  #     #     ./gradlew test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: â˜• Setting up Java (17)
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "adopt"
          cache: gradle
      - name: ğŸ—ï¸ Build ZenSpace
        if: always()
        run: |
          cd ./packages/server
          chmod +x gradlew
          ./gradlew --no-daemon jib --image=ghcr.io/brys0/zenspace:latest -Djib.to.auth.username=Brys0 -Djib.to.auth.password=${{secrets.SECRET_TOKEN}}
